<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate existing countries
        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();
        Schema::enableForeignKeyConstraints();

        // 1. Seed All Countries of the World
        $countriesList = [
            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Aland Islands', 'code' => 'AX'],
            ['name' => 'Albania', 'code' => 'AL'],
            ['name' => 'Algeria', 'code' => 'DZ'],
            ['name' => 'American Samoa', 'code' => 'AS'],
            ['name' => 'Andorra', 'code' => 'AD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Anguilla', 'code' => 'AI'],
            ['name' => 'Antarctica', 'code' => 'AQ'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['name' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Armenia', 'code' => 'AM'],
            ['name' => 'Aruba', 'code' => 'AW'],
            ['name' => 'Australia', 'code' => 'AU'],
            ['name' => 'Austria', 'code' => 'AT'],
            ['name' => 'Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Bahamas', 'code' => 'BS'],
            ['name' => 'Bahrain', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Belarus', 'code' => 'BY'],
            ['name' => 'Belgium', 'code' => 'BE'],
            ['name' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Bermuda', 'code' => 'BM'],
            ['name' => 'Bhutan', 'code' => 'BT'],
            ['name' => 'Bolivia', 'code' => 'BO'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Brazil', 'code' => 'BR'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO'],
            ['name' => 'British Virgin Islands', 'code' => 'VG'],
            ['name' => 'Brunei', 'code' => 'BN'],
            ['name' => 'Bulgaria', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Cambodia', 'code' => 'KH'],
            ['name' => 'Cameroon', 'code' => 'CM'],
            ['name' => 'Canada', 'code' => 'CA'],
            ['name' => 'Cape Verde', 'code' => 'CV'],
            ['name' => 'Cayman Islands', 'code' => 'KY'],
            ['name' => 'Central African Republic', 'code' => 'CF'],
            ['name' => 'Chad', 'code' => 'TD'],
            ['name' => 'Chile', 'code' => 'CL'],
            ['name' => 'China', 'code' => 'CN'],
            ['name' => 'Christmas Island', 'code' => 'CX'],
            ['name' => 'Cocos Islands', 'code' => 'CC'],
            ['name' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Comoros', 'code' => 'KM'],
            ['name' => 'Republic of the Congo', 'code' => 'CG'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'CD'],
            ['name' => 'Cook Islands', 'code' => 'CK'],
            ['name' => 'Costa Rica', 'code' => 'CR'],
            ['name' => 'Ivory Coast', 'code' => 'CI'],
            ['name' => 'Croatia', 'code' => 'HR'],
            ['name' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Czech Republic', 'code' => 'CZ'],
            ['name' => 'Denmark', 'code' => 'DK'],
            ['name' => 'Djibouti', 'code' => 'DJ'],
            ['name' => 'Dominica', 'code' => 'DM'],
            ['name' => 'Dominican Republic', 'code' => 'DO'],
            ['name' => 'Ecuador', 'code' => 'EC'],
            ['name' => 'Egypt', 'code' => 'EG'],
            ['name' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Estonia', 'code' => 'EE'],
            ['name' => 'Ethiopia', 'code' => 'ET'],
            ['name' => 'Falkland Islands', 'code' => 'FK'],
            ['name' => 'Faroe Islands', 'code' => 'FO'],
            ['name' => 'Fiji', 'code' => 'FJ'],
            ['name' => 'Finland', 'code' => 'FI'],
            ['name' => 'France', 'code' => 'FR'],
            ['name' => 'French Guiana', 'code' => 'GF'],
            ['name' => 'French Polynesia', 'code' => 'PF'],
            ['name' => 'French Southern Territories', 'code' => 'TF'],
            ['name' => 'Gabon', 'code' => 'GA'],
            ['name' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Georgia', 'code' => 'GE'],
            ['name' => 'Germany', 'code' => 'DE'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Gibraltar', 'code' => 'GI'],
            ['name' => 'Greece', 'code' => 'GR'],
            ['name' => 'Greenland', 'code' => 'GL'],
            ['name' => 'Grenada', 'code' => 'GD'],
            ['name' => 'Guadeloupe', 'code' => 'GP'],
            ['name' => 'Guam', 'code' => 'GU'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guernsey', 'code' => 'GG'],
            ['name' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Hong Kong', 'code' => 'HK'],
            ['name' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Iceland', 'code' => 'IS'],
            ['name' => 'India', 'code' => 'IN'],
            ['name' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Ireland', 'code' => 'IE'],
            ['name' => 'Isle of Man', 'code' => 'IM'],
            ['name' => 'Israel', 'code' => 'IL'],
            ['name' => 'Italy', 'code' => 'IT'],
            ['name' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Japan', 'code' => 'JP'],
            ['name' => 'Jersey', 'code' => 'JE'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Kiribati', 'code' => 'KI'],
            ['name' => 'Kosovo', 'code' => 'XK'],
            ['name' => 'Kuwait', 'code' => 'KW'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Laos', 'code' => 'LA'],
            ['name' => 'Latvia', 'code' => 'LV'],
            ['name' => 'Lebanon', 'code' => 'LB'],
            ['name' => 'Lesotho', 'code' => 'LS'],
            ['name' => 'Liberia', 'code' => 'LR'],
            ['name' => 'Libya', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'code' => 'LI'],
            ['name' => 'Lithuania', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Macau', 'code' => 'MO'],
            ['name' => 'Macedonia', 'code' => 'MK'],
            ['name' => 'Madagascar', 'code' => 'MG'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Maldives', 'code' => 'MV'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Marshall Islands', 'code' => 'MH'],
            ['name' => 'Martinique', 'code' => 'MQ'],
            ['name' => 'Mauritania', 'code' => 'MR'],
            ['name' => 'Mauritius', 'code' => 'MU'],
            ['name' => 'Mayotte', 'code' => 'YT'],
            ['name' => 'Mexico', 'code' => 'MX'],
            ['name' => 'Micronesia', 'code' => 'FM'],
            ['name' => 'Moldova', 'code' => 'MD'],
            ['name' => 'Monaco', 'code' => 'MC'],
            ['name' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Montenegro', 'code' => 'ME'],
            ['name' => 'Montserrat', 'code' => 'MS'],
            ['name' => 'Morocco', 'code' => 'MA'],
            ['name' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Myanmar', 'code' => 'MM'],
            ['name' => 'Namibia', 'code' => 'NA'],
            ['name' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Netherlands', 'code' => 'NL'],
            ['name' => 'New Caledonia', 'code' => 'NC'],
            ['name' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'code' => 'NI'],
            ['name' => 'Niger', 'code' => 'NE'],
            ['name' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'Niue', 'code' => 'NU'],
            ['name' => 'Norfolk Island', 'code' => 'NF'],
            ['name' => 'North Korea', 'code' => 'KP'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP'],
            ['name' => 'Norway', 'code' => 'NO'],
            ['name' => 'Oman', 'code' => 'OM'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Palau', 'code' => 'PW'],
            ['name' => 'Palestinian Territory', 'code' => 'PS'],
            ['name' => 'Panama', 'code' => 'PA'],
            ['name' => 'Papua New Guinea', 'code' => 'PG'],
            ['name' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'Philippines', 'code' => 'PH'],
            ['name' => 'Pitcairn', 'code' => 'PN'],
            ['name' => 'Poland', 'code' => 'PL'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Puerto Rico', 'code' => 'PR'],
            ['name' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Reunion', 'code' => 'RE'],
            ['name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Russia', 'code' => 'RU'],
            ['name' => 'Rwanda', 'code' => 'RW'],
            ['name' => 'Saint Barthelemy', 'code' => 'BL'],
            ['name' => 'Saint Helena', 'code' => 'SH'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['name' => 'Saint Lucia', 'code' => 'LC'],
            ['name' => 'Saint Martin', 'code' => 'MF'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['name' => 'Samoa', 'code' => 'WS'],
            ['name' => 'San Marino', 'code' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST'],
            ['name' => 'Saudi Arabia', 'code' => 'SA'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Serbia', 'code' => 'RS'],
            ['name' => 'Seychelles', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singapore', 'code' => 'SG'],
            ['name' => 'Sint Maarten', 'code' => 'SX'],
            ['name' => 'Slovakia', 'code' => 'SK'],
            ['name' => 'Slovenia', 'code' => 'SI'],
            ['name' => 'Solomon Islands', 'code' => 'SB'],
            ['name' => 'Somalia', 'code' => 'SO'],
            ['name' => 'South Africa', 'code' => 'ZA'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            ['name' => 'South Korea', 'code' => 'KR'],
            ['name' => 'South Sudan', 'code' => 'SS'],
            ['name' => 'Spain', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Sudan', 'code' => 'SD'],
            ['name' => 'Suriname', 'code' => 'SR'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
            ['name' => 'Swaziland', 'code' => 'SZ'],
            ['name' => 'Sweden', 'code' => 'SE'],
            ['name' => 'Switzerland', 'code' => 'CH'],
            ['name' => 'Syria', 'code' => 'SY'],
            ['name' => 'Taiwan', 'code' => 'TW'],
            ['name' => 'Tajikistan', 'code' => 'TJ'],
            ['name' => 'Tanzania', 'code' => 'TZ'],
            ['name' => 'Thailand', 'code' => 'TH'],
            ['name' => 'Timor-Leste', 'code' => 'TL'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Tokelau', 'code' => 'TK'],
            ['name' => 'Tonga', 'code' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['name' => 'Tunisia', 'code' => 'TN'],
            ['name' => 'Turkey', 'code' => 'TR'],
            ['name' => 'Turkmenistan', 'code' => 'TM'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC'],
            ['name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'United Arab Emirates', 'code' => 'AE'],
            ['name' => 'United Kingdom', 'code' => 'GB'],
            ['name' => 'United States', 'code' => 'US'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'code' => 'VU'],
            ['name' => 'Vatican', 'code' => 'VA'],
            ['name' => 'Venezuela', 'code' => 'VE'],
            ['name' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF'],
            ['name' => 'Western Sahara', 'code' => 'EH'],
            ['name' => 'Yemen', 'code' => 'YE'],
            ['name' => 'Zambia', 'code' => 'ZM'],
            ['name' => 'Zimbabwe', 'code' => 'ZW'],
        ];

        // Format and insert in chunks to avoid database limits
        $countries = [];
        $index = 1;
        foreach ($countriesList as $country) {
            $countries[] = [
                'id' => $index,
                'name' => $country['name'],
                'code' => $country['code'],
                'created_at' => now(),
                'updated_at' => now()
            ];
            $index++;
        }

        $chunks = array_chunk($countries, 50);
        foreach ($chunks as $chunk) {
            DB::table('countries')->insert($chunk);
        }

        // 2. Seed BD Divisions (Make sure country_id maps to Bangladesh's new ID in the list)
        // Bangladesh is 19th in the alphabetical list (which is ID 19)
        $bdId = 19;
        
        Schema::disableForeignKeyConstraints();
        DB::table('divisions')->truncate();
        DB::table('districts')->truncate();
        DB::table('areas')->truncate();
        Schema::enableForeignKeyConstraints();

        $divisions = [
            ['id' => 1, 'country_id' => $bdId, 'name' => 'Dhaka', 'name_bn' => 'ঢাকা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'country_id' => $bdId, 'name' => 'Chattogram', 'name_bn' => 'চট্টগ্রাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'country_id' => $bdId, 'name' => 'Rajshahi', 'name_bn' => 'রাজশাহী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'country_id' => $bdId, 'name' => 'Khulna', 'name_bn' => 'খুলনা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'country_id' => $bdId, 'name' => 'Barishal', 'name_bn' => 'বরিশাল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'country_id' => $bdId, 'name' => 'Sylhet', 'name_bn' => 'সিলেট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'country_id' => $bdId, 'name' => 'Rangpur', 'name_bn' => 'রংপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'country_id' => $bdId, 'name' => 'Mymensingh', 'name_bn' => 'ময়মনসিংহ', 'created_at' => now(), 'updated_at' => now()],
        ];
        DB::table('divisions')->insert($divisions);

        // 3. Seed BD Districts (64 Districts)
        $districts = [
            ['id' => 1, 'division_id' => 1, 'name' => 'Dhaka', 'name_bn' => 'ঢাকা'],
            ['id' => 2, 'division_id' => 1, 'name' => 'Gazipur', 'name_bn' => 'গাজীপুর'],
            ['id' => 3, 'division_id' => 1, 'name' => 'Narayanganj', 'name_bn' => 'নারায়ণগঞ্জ'],
            ['id' => 4, 'division_id' => 1, 'name' => 'Munshiganj', 'name_bn' => 'মুন্সীগঞ্জ'],
            ['id' => 5, 'division_id' => 1, 'name' => 'Manikganj', 'name_bn' => 'মানিকগঞ্জ'],
            ['id' => 6, 'division_id' => 1, 'name' => 'Narsingdi', 'name_bn' => 'নরসিংদী'],
            ['id' => 7, 'division_id' => 1, 'name' => 'Faridpur', 'name_bn' => 'ফরিদপুর'],
            ['id' => 8, 'division_id' => 1, 'name' => 'Gopalganj', 'name_bn' => 'গোপালগঞ্জ'],
            ['id' => 9, 'division_id' => 1, 'name' => 'Madaripur', 'name_bn' => 'মাদারীপুর'],
            ['id' => 10, 'division_id' => 1, 'name' => 'Rajbari', 'name_bn' => 'রাজবাড়ী'],
            ['id' => 11, 'division_id' => 1, 'name' => 'Shariatpur', 'name_bn' => 'শরীয়তপুর'],
            ['id' => 12, 'division_id' => 1, 'name' => 'Tangail', 'name_bn' => 'टाঙ্গাইল'],
            ['id' => 13, 'division_id' => 1, 'name' => 'Kishoreganj', 'name_bn' => 'কিশোরগঞ্জ'],
            ['id' => 14, 'division_id' => 2, 'name' => 'Chattogram', 'name_bn' => 'চট্টগ্রাম'],
            ['id' => 15, 'division_id' => 2, 'name' => 'Cox\'s Bazar', 'name_bn' => 'কক্সবাজার'],
            ['id' => 16, 'division_id' => 2, 'name' => 'Cumilla', 'name_bn' => 'কুমিল্লা'],
            ['id' => 17, 'division_id' => 2, 'name' => 'Feni', 'name_bn' => 'ফেনী'],
            ['id' => 18, 'division_id' => 2, 'name' => 'Brahmanbaria', 'name_bn' => 'ব্রাহ্মণবাড়িয়া'],
            ['id' => 19, 'division_id' => 2, 'name' => 'Noakhali', 'name_bn' => 'নোয়াখালী'],
            ['id' => 20, 'division_id' => 2, 'name' => 'Lakshmipur', 'name_bn' => 'লক্ষ্মীপুর'],
            ['id' => 21, 'division_id' => 2, 'name' => 'Chandpur', 'name_bn' => 'চাঁদপুর'],
            ['id' => 22, 'division_id' => 2, 'name' => 'Rangamati', 'name_bn' => 'রাঙ্গামাটি'],
            ['id' => 23, 'division_id' => 2, 'name' => 'Khagrachhari', 'name_bn' => 'খাগড়াছড়ি'],
            ['id' => 24, 'division_id' => 2, 'name' => 'Bandarban', 'name_bn' => 'বান্দরবান'],
            ['id' => 25, 'division_id' => 3, 'name' => 'Rajshahi', 'name_bn' => 'রাজশাহী'],
            ['id' => 26, 'division_id' => 3, 'name' => 'Bogura', 'name_bn' => 'বগুড়া'],
            ['id' => 27, 'division_id' => 3, 'name' => 'Pabna', 'name_bn' => 'পাবনা'],
            ['id' => 28, 'division_id' => 3, 'name' => 'Natore', 'name_bn' => 'নাটোর'],
            ['id' => 29, 'division_id' => 3, 'name' => 'Joypurhat', 'name_bn' => 'জয়পুরহাট'],
            ['id' => 30, 'division_id' => 3, 'name' => 'Naogaon', 'name_bn' => 'নওগাঁ'],
            ['id' => 31, 'division_id' => 3, 'name' => 'Sirajganj', 'name_bn' => 'সিরাজগঞ্জ'],
            ['id' => 32, 'division_id' => 3, 'name' => 'Chapainawabganj', 'name_bn' => 'চাঁপাইনবাবগঞ্জ'],
            ['id' => 33, 'division_id' => 4, 'name' => 'Khulna', 'name_bn' => 'খুলনা'],
            ['id' => 34, 'division_id' => 4, 'name' => 'Jashore', 'name_bn' => 'যশোর'],
            ['id' => 35, 'division_id' => 4, 'name' => 'Satkhira', 'name_bn' => 'সাতক্ষীরা'],
            ['id' => 36, 'division_id' => 4, 'name' => 'Bagerhat', 'name_bn' => 'বাগেরহাট'],
            ['id' => 37, 'division_id' => 4, 'name' => 'Kushtia', 'name_bn' => 'কুষ্টিয়া'],
            ['id' => 38, 'division_id' => 4, 'name' => 'Meherpur', 'name_bn' => 'মেহেরপুর'],
            ['id' => 39, 'division_id' => 4, 'name' => 'Chuadanga', 'name_bn' => 'চুয়াডাঙ্গা'],
            ['id' => 40, 'division_id' => 4, 'name' => 'Jhenaidah', 'name_bn' => 'ঝিনাইদহ'],
            ['id' => 41, 'division_id' => 4, 'name' => 'Magura', 'name_bn' => 'মাগুরা'],
            ['id' => 42, 'division_id' => 4, 'name' => 'Narail', 'name_bn' => 'নড়াইল'],
            ['id' => 43, 'division_id' => 5, 'name' => 'Barishal', 'name_bn' => 'বরিশাল'],
            ['id' => 44, 'division_id' => 5, 'name' => 'Patuakhali', 'name_bn' => 'পটুয়াখালী'],
            ['id' => 45, 'division_id' => 5, 'name' => 'Bhola', 'name_bn' => 'ভোলা'],
            ['id' => 46, 'division_id' => 5, 'name' => 'Pirojpur', 'name_bn' => 'পিরোজপুর'],
            ['id' => 47, 'division_id' => 5, 'name' => 'Barguna', 'name_bn' => 'বরগুনা'],
            ['id' => 48, 'division_id' => 5, 'name' => 'Jhalokati', 'name_bn' => 'ঝালকাঠি'],
            ['id' => 49, 'division_id' => 6, 'name' => 'Sylhet', 'name_bn' => 'সিলেট'],
            ['id' => 50, 'division_id' => 6, 'name' => 'Moulvibazar', 'name_bn' => 'মৌলভীবাজার'],
            ['id' => 51, 'division_id' => 6, 'name' => 'Habiganj', 'name_bn' => 'হবিগঞ্জ'],
            ['id' => 52, 'division_id' => 6, 'name' => 'Sunamganj', 'name_bn' => 'সুনামগঞ্জ'],
            ['id' => 53, 'division_id' => 7, 'name' => 'Rangpur', 'name_bn' => 'রংপুর'],
            ['id' => 54, 'division_id' => 7, 'name' => 'Dinajpur', 'name_bn' => 'দিনাজপুর'],
            ['id' => 55, 'division_id' => 7, 'name' => 'Kurigram', 'name_bn' => 'কুড়িগ্রাম'],
            ['id' => 56, 'division_id' => 7, 'name' => 'Gaibandha', 'name_bn' => 'গাইবান্ধা'],
            ['id' => 57, 'division_id' => 7, 'name' => 'Lalmonirhat', 'name_bn' => 'লালমনিরহাট'],
            ['id' => 58, 'division_id' => 7, 'name' => 'Nilphamari', 'name_bn' => 'নীলফামারী'],
            ['id' => 59, 'division_id' => 7, 'name' => 'Panchagarh', 'name_bn' => 'পঞ্চগড়'],
            ['id' => 60, 'division_id' => 7, 'name' => 'Thakurgaon', 'name_bn' => 'ঠাকুরগাঁও'],
            ['id' => 61, 'division_id' => 8, 'name' => 'Mymensingh', 'name_bn' => 'ময়মনসিংহ'],
            ['id' => 62, 'division_id' => 8, 'name' => 'Jamalpur', 'name_bn' => 'জামালপুর'],
            ['id' => 63, 'division_id' => 8, 'name' => 'Netrokona', 'name_bn' => 'নেত্রকোনা'],
            ['id' => 64, 'division_id' => 8, 'name' => 'Sherpur', 'name_bn' => 'শেরপুর'],
        ];

        foreach ($districts as &$district) {
            $district['created_at'] = now();
            $district['updated_at'] = now();
        }
        DB::table('districts')->insert($districts);

        // 4. Seed sample Areas
        $areas = [
            ['id' => 1, 'district_id' => 1, 'name' => 'Mirpur', 'name_bn' => 'মিরপুর'],
            ['id' => 2, 'district_id' => 1, 'name' => 'Uttara', 'name_bn' => 'উত্তরা'],
            ['id' => 3, 'district_id' => 1, 'name' => 'Dhanmondi', 'name_bn' => 'ধানমণ্ডি'],
            ['id' => 4, 'district_id' => 1, 'name' => 'Gulshan', 'name_bn' => 'গুলশান'],
            ['id' => 5, 'district_id' => 1, 'name' => 'Banani', 'name_bn' => 'বনানী'],
            ['id' => 6, 'district_id' => 1, 'name' => 'Motijheel', 'name_bn' => 'মতিঝিল'],
            ['id' => 7, 'district_id' => 1, 'name' => 'Mohammadpur', 'name_bn' => 'মোহাম্মদপুর'],
            ['id' => 8, 'district_id' => 1, 'name' => 'Badda', 'name_bn' => 'বাড্ডা'],
            ['id' => 9, 'district_id' => 14, 'name' => 'Halishahar', 'name_bn' => 'হালিশহর'],
            ['id' => 10, 'district_id' => 14, 'name' => 'Panchlaish', 'name_bn' => 'পাচঁলাইশ'],
            ['id' => 11, 'district_id' => 14, 'name' => 'Kotwali', 'name_bn' => 'কোতোয়ালী'],
            ['id' => 12, 'district_id' => 14, 'name' => 'Double Mooring', 'name_bn' => 'ডবলমুরিং'],
        ];

        foreach ($areas as &$area) {
            $area['created_at'] = now();
            $area['updated_at'] = now();
        }
        DB::table('areas')->insert($areas);
    }
}
